:"Pathogen plugin in order to handel the installation of every other plugin
execute pathogen#infect()
execute pathogen#helptags()

:set wildmenu
:set guioptions-=m
:set guioptions-=T
:set smartcase
:set number

"Highlight search as you type
:set hlsearch
:set incsearch

:set expandtab
:set tabstop=2 shiftwidth=2 softtabstop=2
:set autoindent
:set showmatch

"Allow to switch buffers without having to save its changes
:set hidden

"Do not create backup files
:set nobackup
:set noswapfile

"Leader
:let mapleader=","

syntax on
filetype on
filetype indent on
filetype plugin on

"Disable annoying beep sound when errors ocurr, it just clears the value to empty
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Maximize window on start
if has("gui_running")
  " GUI is running or is about to start.
  " Maximize gvim windows.
  set lines=999 columns=999
endif

" Colorscheme 
if has("gui_running")
  :set background=dark
  :set t_Co=16
  :colorscheme solarized
else
  :colorscheme default
endif

" REMAPS

" nerdtree
nmap <F9> :NERDTreeToggle<CR>
" tagbar
nmap <F10> :TagbarToggle<CR>

" minibuffer explorer
nmap <Leader>bd :MBEbd<CR>
nmap <Leader>n :MBEbn<CR>
nmap <Leader>p :MBEbp<CR>
"" most recent
nmap <Leader>mn :MBEbf<CR>
"" most previous
nmap <Leader>mp :MBEbb<CR>

" Move around buffers
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

"Not working, review when possible...
"Yank/paste to the OS clipboard
"nnoremap <leader>y "+y
"nnoremap <leader>Y "+yy
"nnoremap <leader>p "+p
"nnoremap <leader>P "+P

" Jump to matching pairs
nnoremap <tab> %
vnoremap <tab> %

" : => ;
nnoremap ; :

"Sudo into file to make changes
cmap w!! w !sudo tee % >/dev/null

"ctrlp.vim plugin => find files
"ag plugin => find words in files
"align


inoremap <Leader><tab> <c-n>
"Tab remap to omni-complete
"function! InsertTabWrapper()
"   let col = col('.') - 1
"   if !col || getline('.')[col - 1] !~ '\k'
"       return "\<tab>"
"   else
"       return "\<c-p>"
"   endif
"endfunction

" PLUGINS

" syntastic
let g:syntastic_auto_jump=1
let g:syntastic_auto_loc_list=1

" easytags
let g:easytags_updatetime_warn=0
