---
- name: Install java
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - openjdk-7-jdk
    - ant

- name: Add java home to correct path
  lineinfile: line="export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386" dest=~/.bash_profile state=present create=yes

- name: Download Android SDK
  get_url: url=https://dl.google.com/android/android-sdk_r22.6.2-linux.tgz dest=/tmp

- name: Untar Android SDK
  command: tar zxf android-sdk_r22.6.2-linux.tgz chdir=/tmp

- name: Move Android SDK to home folder
  command: cp android-sdk-linux ~/ -rf chdir=/tmp

- name: Add android to path variable
  lineinfile: line="PATH=$HOME/android-sdk-linux/tools:$HOME/android-sdk-linux/platform-tools:$PATH" dest=~/.bash_profile state=present create=yes
