---
- name: Install vim from package repository
  apt: name={{ item }} state=latest
  with_items:
    - vim
    - exuberant-ctags
  sudo: true

- name: Add vim as the default editor
  lineinfile: line="export EDITOR='vim'" state=present dest=~/.bash_profile create=yes

# Download settings from own repository
- name: Download vim folder
  git: repo=https://github.com/Radyz/Vim-Radyz.git dest=~/.vim

- name: Create symlink to vimrc
  file: src=~/.vim/.vimrc dest=~/.vimrc state=link

- name: Create symlink to pathogen
  file: src=~/.vim/autoload/vim-pathogen/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim state=link

- name: Create symlink to hybrid theme
  file: src=~/.vim/colors/hybrid/colors/hybrid.vim dest=~/.vim/colors/hybrid.vim state=link

- name: Complete ropevim setup
  command: python setup.py install chdir=/home/{{ user }}/.vim/bundle/ropevim
  sudo: true
