---
# There isn't a ppa to install latest version so it needs to be done manually

- name: Install dependencies
  apt: name={{ item }} state=latest
  sudo: true
  with_items: 
  - libfontconfig1
  - openjdk-7-jre

- name: Download binary
  get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/{{ file }}.tar.bz2 dest=/tmp

- name: Untar binary download
  command: tar xjf {{ file }}.tar.bz2 chdir=/tmp

- name: Move binary to /opt folder
  command: cp {{ file }} /opt -rf chdir=/tmp
  sudo: true

- name: Set symlink to binary
  file: src=/opt/{{ file }}/bin/phantomjs state=link path=/usr/bin/phantomjs
  sudo: true
